// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: message.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace gRPC.Message {
  public static partial class gRPCService
  {
    static readonly string __ServiceName = "gRPC.Message.gRPCService";

    static readonly grpc::Marshaller<global::gRPC.Message.AddUserRequest> __Marshaller_gRPC_Message_AddUserRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::gRPC.Message.AddUserRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::gRPC.Message.Response> __Marshaller_gRPC_Message_Response = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::gRPC.Message.Response.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::gRPC.Message.GetUsersRequest> __Marshaller_gRPC_Message_GetUsersRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::gRPC.Message.GetUsersRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::gRPC.Message.DeleteUserRequest> __Marshaller_gRPC_Message_DeleteUserRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::gRPC.Message.DeleteUserRequest.Parser.ParseFrom);

    static readonly grpc::Method<global::gRPC.Message.AddUserRequest, global::gRPC.Message.Response> __Method_AddUser = new grpc::Method<global::gRPC.Message.AddUserRequest, global::gRPC.Message.Response>(
        grpc::MethodType.Unary,
        __ServiceName,
        "AddUser",
        __Marshaller_gRPC_Message_AddUserRequest,
        __Marshaller_gRPC_Message_Response);

    static readonly grpc::Method<global::gRPC.Message.GetUsersRequest, global::gRPC.Message.Response> __Method_GetUsers = new grpc::Method<global::gRPC.Message.GetUsersRequest, global::gRPC.Message.Response>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetUsers",
        __Marshaller_gRPC_Message_GetUsersRequest,
        __Marshaller_gRPC_Message_Response);

    static readonly grpc::Method<global::gRPC.Message.DeleteUserRequest, global::gRPC.Message.Response> __Method_DeleteUser = new grpc::Method<global::gRPC.Message.DeleteUserRequest, global::gRPC.Message.Response>(
        grpc::MethodType.Unary,
        __ServiceName,
        "DeleteUser",
        __Marshaller_gRPC_Message_DeleteUserRequest,
        __Marshaller_gRPC_Message_Response);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::gRPC.Message.MessageReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of gRPCService</summary>
    public abstract partial class gRPCServiceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::gRPC.Message.Response> AddUser(global::gRPC.Message.AddUserRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::gRPC.Message.Response> GetUsers(global::gRPC.Message.GetUsersRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::gRPC.Message.Response> DeleteUser(global::gRPC.Message.DeleteUserRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for gRPCService</summary>
    public partial class gRPCServiceClient : grpc::ClientBase<gRPCServiceClient>
    {
      /// <summary>Creates a new client for gRPCService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public gRPCServiceClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for gRPCService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public gRPCServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected gRPCServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected gRPCServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::gRPC.Message.Response AddUser(global::gRPC.Message.AddUserRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return AddUser(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::gRPC.Message.Response AddUser(global::gRPC.Message.AddUserRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_AddUser, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::gRPC.Message.Response> AddUserAsync(global::gRPC.Message.AddUserRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return AddUserAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::gRPC.Message.Response> AddUserAsync(global::gRPC.Message.AddUserRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_AddUser, null, options, request);
      }
      public virtual global::gRPC.Message.Response GetUsers(global::gRPC.Message.GetUsersRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetUsers(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::gRPC.Message.Response GetUsers(global::gRPC.Message.GetUsersRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetUsers, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::gRPC.Message.Response> GetUsersAsync(global::gRPC.Message.GetUsersRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetUsersAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::gRPC.Message.Response> GetUsersAsync(global::gRPC.Message.GetUsersRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetUsers, null, options, request);
      }
      public virtual global::gRPC.Message.Response DeleteUser(global::gRPC.Message.DeleteUserRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return DeleteUser(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::gRPC.Message.Response DeleteUser(global::gRPC.Message.DeleteUserRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_DeleteUser, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::gRPC.Message.Response> DeleteUserAsync(global::gRPC.Message.DeleteUserRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return DeleteUserAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::gRPC.Message.Response> DeleteUserAsync(global::gRPC.Message.DeleteUserRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_DeleteUser, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override gRPCServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new gRPCServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(gRPCServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_AddUser, serviceImpl.AddUser)
          .AddMethod(__Method_GetUsers, serviceImpl.GetUsers)
          .AddMethod(__Method_DeleteUser, serviceImpl.DeleteUser).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, gRPCServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_AddUser, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::gRPC.Message.AddUserRequest, global::gRPC.Message.Response>(serviceImpl.AddUser));
      serviceBinder.AddMethod(__Method_GetUsers, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::gRPC.Message.GetUsersRequest, global::gRPC.Message.Response>(serviceImpl.GetUsers));
      serviceBinder.AddMethod(__Method_DeleteUser, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::gRPC.Message.DeleteUserRequest, global::gRPC.Message.Response>(serviceImpl.DeleteUser));
    }

  }
}
#endregion
